### PR TITLE
Template for the GSoC proposals

### PR DESCRIPTION
**Pull request by ArazAbishov**
- Template for the GSoC proposal
 - Added links to easy and help-wanted issues on GitHub for students to look at

### CODE REVIEW

**Comment by ArazAbishov** [comment]
That's pretty cool actually, I didn't know about gsocguides. I will ad the link to the gsoc page then 👍

**Comment by ArazAbishov** [comment]
@raphlinus Should I merge it myself? :)

**Comment by raphlinus** [comment]
I'll merge it now, but if it's approved by me, cmyr, or vlovich, you can feel free to merge it yourself. Thanks!

**Comment by ArazAbishov** [comment]
Will note for the future, thanks!

**Pull request merged**
