### PR TITLE
Handling Keyboard Actions and Inserting Text

### PR DESCRIPTION
**Pull request by rtsuk**
AppKit has facilities for interpreting key events, integrated here. This would partially address #10.

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/EventOverview/HandlingKeyEvents/HandlingKeyEvents.html#//apple_ref/doc/uid/10000060i-CH7-SW13

Sorry for yet another pull request but there's something screwed up with the history in my fork.

### CODE REVIEW

**Comment by raphlinus** [comment]
Looks good. Thanks for your work on this!

**Comment by Sineaggi** [comment]
So now there are two entry points for those functions you modified?

I have code currently trapping directional arrows and sending over the OSX key equivalent. Should all input be handled through a different json command?

**Comment by rtsuk** [comment]
It's not so much a function for every combination of modifiers as much as a function for distinct text editing actions, such as deleting a word backwards or extending the selection by moving to the right. It's worked well for AppKit, I think it will work well here too.

**Comment by Sineaggi** [comment]
Sounds good. But I still wonder, should we have the two entry points defined? One in the json call, one in the do_key switch statement. I can handle one or the other, but having multiple options is bothering me. :)

**Comment by raphlinus** [comment]
I would lean towards doing things the most semantic way, ie `move_up_and_modify_selection` rather than trying to pass in a shift.

**Comment by rtsuk** [comment]
As soon as Raph no longer needs the do_key interface I'd be happy to delete it.

**Pull request merged**
