### PR TITLE
Add depth to clone command in README

### PR DESCRIPTION
**Pull request by steelbrain**
Just like the title says

### CODE REVIEW

**Comment by raphlinus** [comment]
Curious about the motivation. The repo is small enough I wasn't able to see any measurable difference in clone time (about 2s in both cases). Sometimes history is useful.

**Comment by steelbrain** [comment]
Most of the times, history is not as useful and even if it's required, one can easily fetch the history on a shallow clone. This is just to make it copy/paste friendly for the majority.

**Comment by shssoichiro** [comment]
I am personally against using `--depth=1`, because it actually creates more work for git if you later try to pull, if any of the newer commits being pulled in are merges onto an earlier commit than your HEAD. This project is so small at the moment that it probably doesn't matter, but it's caused significant issues for some larger repos (CocoaPods being the most notable).

**Comment by leavengood** [comment]
I think this can be closed since generally it seems most of us don't believe adding the `--depth` param adds much value at this time.

**Comment by raphlinus** [comment]
Agreed.

**Pull request closed without merging**
