### PR TITLE
Fix re-opening file opens empty buffer

### PR DESCRIPTION
**Pull request by rkusa**
Fixes the following bug:

1. Open file X
2. Close file X
3. Open file X again

Results in empty document instead of having file X open again.

Reason is that filenames are not remove from `open_files` when closing all views to a filename.

This PR fixes this behaviour.

### CODE REVIEW

**Comment by rkusa** [comment]
Thanks for the review!

I am also not entirely happy with copying the value. The only other solutions I found were to move the `open_files.remove` into the `let has_views = {}` block

```rust
let buf_id = self.views.remove(view_id).expect("missing buffer id when closing view");
let has_views = {
    let editor = self.buffers.get(&buf_id).expect("missing editor when closing view");
    let mut editor = editor.lock().unwrap();
    editor.remove_view(view_id);
    let has_views = editor.has_views();
    if !has_views {
      if let Some(path) = editor.get_path() {
          self.open_files.remove(path);
      }
    }
    has_views
};

if !has_views {
    self.buffers.remove(&buf_id);
}
```

or into the `if !has_views {}` block. (basically your suggestion `if let Some(path) = editor.lock().unwrap().get_path()`, but we have to retrieve `editor` first)

```rust
let buf_id = self.views.remove(view_id).expect("missing buffer id when closing view");
let has_views = {
    let editor = self.buffers.get(&buf_id).expect("missing editor when closing view");
    let mut editor = editor.lock().unwrap();
    editor.remove_view(view_id);
    editor.has_views()
};

if !has_views {
    self.buffers.remove(&buf_id);
    if let Some(path) = self.buffers.get(&buf_id).unwrap().lock().unwrap().get_path() {
        self.open_files.remove(path);
    }
}
```

I kind of dislike both, but still happy to adjust the PR. Or maybe you have even a better idea?

**Comment by cmyr** [comment]
yea I remember this being a bit of a headache, which is why we're using the block in the first place. Lemme fire up an editor and play around for a sec. :)

**Comment by rkusa** [comment]
Is cloning the Editor better then copying the path? If so:

```rust
let editor = {
    let editor = self.buffers.get(&buf_id).expect("missing editor when closing view");
    editor.clone()
};
```

So now I am letting you play ;-)

**Comment by cmyr** [comment]
Okay, I'm back to preferring your original solution. :)

We don't really need to worry about the copy as a performance issue (closing views happens rarely), it's just something I'm trying to train myself to treat as codesmell, in Rust.

**Comment by raphlinus** [comment]
Thanks, appreciate the fix!

**Pull request merged**
