### PR TITLE
Add pronunciation to readme

### PR DESCRIPTION
**Pull request by shaunlebron**
Easier to spread the word on something if people immediately know how to pronounce it. [source]( https://www.youtube.com/watch?v=SKtQgFBRUvQ#t=18s)

screen shot 2017-07-25 at 3 14 16 pm

### CODE REVIEW

**Comment by shaunlebron** [comment]
I signed the CLA.

Agreed about the strange spelling "igh".  Luckily it can only be pronounced one way in English!

**Comment by jeanm** [comment]
Some alternative ways of explaining it:
* Like *seye* in *bullseye*
* `/zaɪ/`
* Like *si* in *quasi* (won't work for everyone, since some people say `/kwɑzi/`)
* Like *sly*, but without the *l* (not quite)

**Comment by eyelash** [comment]
Or maybe just link to https://en.wikipedia.org/wiki/Xi_%28letter%29 which includes pronunciation?

**Comment by raphlinus** [comment]
This is fine as is, thanks! Linking to Wikipedia is not really going to work because the pronunciation of the Greek letter depends on context. My choice of "zigh" is somewhat arbitrary.

**Pull request merged**
