### PR TITLE
Fix Unicode 9.0 discrepancies

### PR DESCRIPTION
**Pull request by cbreeden**
Fixes: #262 

This is any attempt to fix some test failures from the Unicode 9.0 line break unit tests.  A few things to note about this PR:

1. I have added `linebreaktest.txt` which can be used for unit tests.  I have commented out the unit tests that used custom handling of numeric-like sequences.  You can see which were commented out here e31524fcaf09b75deb7d6faae47d415eda848807.
2. I'm not entirely sure that [this line](https://github.com/google/xi-editor/commit/e31524fcaf09b75deb7d6faae47d415eda848807#diff-00d31ae7cb5cea5cdd929eef5f468d21R357) is handling all cases correctly.  It might be worth taking a look into this, as I _feel_ that I might be able to construct a test example which could fail along these lines.

### CODE REVIEW

**Comment by cbreeden** [comment]
I signed it!

**Comment by cbreeden** [comment]
Thanks, I'd wouldn't definitely appreciate a second pair of eyes.  In case you have some questions, (and since the patch is so small), I can briefly explain the reasoning here:

The following two modifications seem like the straight forward way to handling the [LB9](http://unicode.org/reports/tr14/#BreakingRules), basically where `ZWJ` is treated as you would treat `CM`.

```python
           if R in ['CM', 'ZWJ'] and L in ['BK', 'CR', 'LF', 'NL', 'SP', 'ZW']:
```
and
```python
          elif R in ['CM', 'ZWJ'] and L not in ['BK', 'CR', 'LF', 'NL', 'SP', 'ZW']:
```

One issue is when `ZWJ` is on the left.  We need to treat `ZWJ`, like we do with `CM`, as an `AL` except for the case when `[ID|EB|EM]` is on the right.  This is the purpose of the following conditional:

```python
            elif L == 'ZWJ' and R not in ['ID', 'EB', 'EM']:
                #handling for LB10
                l_with_cm = 2  # AL
                bk = t['AL' + '|' + R]
```

Ignoring the whole `l_with_cm` part is enough to fix all but 3 unit tests from LineBreakTest.txt.  And the `l_with_cm` part is the part I am least comfortable with.  The `l_with_cm` along with the `elif R in ['CM', 'ZWJ']` part which assigns `state = l_with_cm` is logically equivalent to having a special case for  `ZWJ [ CM | ZWJ ]` to be treated as an `AL`.

The test case to have in mind is `ZWJ x CM - [ID|EB|EM]`.  Provided that `ZWJ` doesn't take an identity from a previous character (LB9), which occurs when a `ZWJ` is after a hardbreak or sot, then the `CM` will try to take the identity from `ZWJ`.  Which would render the test as equivalent to `ZWJ x ZWJ x [ID|EB|EM]`.  What should be happening is that the `ZWJ x CM` should be treated as an `AL` and there should be a break between the `CM` and `[ID|EB|EM]`.

**Comment by raphlinus** [comment]
I had a look at this and it seems fine. It's a little more ugliness, but symmetrical with the existing logic, and the underlying rules require a bunch of special-casing. It's nice that you were able to do this without expanding the size of the state machine itself. Also really happy that there are tests, this will definitely help the next time the spec revs.

Thanks again!

**Comment by cbreeden** [comment]
Thanks! I learned a lot with this PR.  I found the Trie data structure for the codepoint -> break class mapping particularly interesting.

> It's nice that you were able to do this without expanding the size of the state machine itself.

The thought did cross my mind, noticing that the 2 MSBs are only used for representing 3 states: no break, soft break, and hard break.  It's quite possible to add a "needs special handling" state which include exactly one additional conditional for only the breaking cases.  But that should definitely be saved as a last resort of course :)

**Pull request merged**
