### PR TITLE
Add support for serializing samples into Chrome trace event

### PR DESCRIPTION
**Pull request by vlovich**
Part 2/2 for #471 provides a mechanism to serialize in-memory samples to a stream.

### CODE REVIEW

**Comment by cmyr** [comment]
It looks like this CI failure is a real one?

**Comment by vlovich** [comment]
Yeah sorry.  I must have added a doc & rebased without testing.  Fixed.

**Comment by raphlinus** [comment]
Looks like there's some work needed to pass the CI tests? I'm very confused because 2edd76c seems to be passing but travis is running 41bc809. I haven't dug in to investigate.

```
   Compiling xi-trace-ffi v0.1.0 (file:///home/travis/build/google/xi-editor/rust/trace-ffi)
error: couldn't read "trace-ffi/examples/c/main.rs": No such file or directory (os error 2)
```

I don't think we have any active intention to use this, but it might be a "nice to have" for other uses.

**Comment by vlovich** [comment]
Fixed in theory.  The commit that should be in this pull request should just be 2602e937d2bb89 which shouldn't have any FFI stuff.

**Pull request merged**
