### PR TITLE
Move notify under feature gate

### PR DESCRIPTION
**Pull request by raphlinus**
The "notify" feature is now optional, but on by default, so no behavior change is expected. (It'll temporarily be off for fuchsia).

### CODE REVIEW

**Comment by raphlinus** [comment]
@cramertj The plan is to actually remove notify altogether from the Cargo.toml in the fuchsia mirror of this repo. With this refactor, that's a two-line delta.

**Comment by cramertj** [comment]
@raphlinus Cool-- I've also been working with acrichto to make it so that you can `cargo vendor` only the dependencies for the features you select, which would solve that problem. That sounds like a good intermediate approach, though.

**Comment by raphlinus** [comment]
@cramertj Yep, I'm looking forward to that, because it would mean not even having to maintain a small diff with upstream.

**Comment by raphlinus** [comment]
Going to merge based on all signs from tests being positive (travis is part-failing because of ancient xcode provisioning)

**Pull request merged**
