### PR TITLE
Documentation cleanup/fixup

### PR DESCRIPTION
**Pull request by cmyr**
A bunch of little cleanup / additions to the docs, in the ongoing battle against entropy.

@ArazAbishov I'm not sure how I should test this locally?

### CODE REVIEW

**Comment by cmyr** [comment]
@raphlinus oh that was an out of date commit. The update doc is now included inline, at the bottom of this page, there should be a link from the update method. Something might've got mangled, though

**Comment by ArazAbishov** [comment]
@cmyr to build page locally, you need to do following:

Ensure that you have Ruby and Bundler installed.
```
gem install bundler
```

One-time setup

```
bundle install --path vendor/bundle
```

> Note: If you’re on Mac OS and this fails installing nokogiri, run brew unlink xz, install, and then brew link xz

Running the site

```
bundle exec jekyll serve
```

Taken from here: https://android.github.io/kotlin-guides/contribute.html 

I can make a PR with similar instructions for xi page as well (in case if that is useful).

**Comment by ArazAbishov** [comment]
@cmyr Yep, we can do that. If we leave it under docs/ directory, it will be visible on the web page as well (among tabs). If that's alright, I can create a PR :)

**Comment by cmyr** [comment]
@ArazAbishov whatever you think is best!

**Pull request merged**
