### PR TITLE
Handling Keyboard Actions and Inserting Text

### PR DESCRIPTION
**Pull request by rtsuk**
AppKit has facilities for interpreting key events. Here's a partial implementation for discussion. I think this is the right aproach but how to plumb it through to the core deserves some consideration.

This would partially address https://github.com/google/xi-editor/issues/10.

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/EventOverview/HandlingKeyEvents/HandlingKeyEvents.html#//apple_ref/doc/uid/10000060i-CH7-SW13

### CODE REVIEW

**Comment by raphlinus** [comment]
Yes, this is the direction I'd like to go. The JSON language to the core should be expanded with lots of small commands generally following the "Responding to Action Messages" methods in NSResponder.

There is some subtlety. In a hypothetical Vim personality, while in command mode, keys should _not_ be interpreted to an "insert" command and then have the letters in that insert reinterpreted as vi-compatible commands.

**Comment by rtsuk** [comment]
Would the Vim personality be implemented in the core? If so, there's a conflict here.

**Comment by raphlinus** [comment]
No, my thinking is that the first line of dispatch of the vim personality is in the front-end. The core will of course do the heavy lifting, and perhaps also the second line of dispatch. This seems broadly compatible with your approach, but will almost certainly require some additional logic in the interpretation of key events. I'm pretty convinced by now that such additional logic is required to handle a vim personality and do input methods correctly in any case.

**Comment by rtsuk** [comment]
Then I will complete this implementation, filling in the core implementation when it is obvious but otherwise leaving them as TBD.

**Comment by rtsuk** [comment]
A rebase went awry. I will restore this tonight.

**Comment by rtsuk** [comment]
Let's see if I can re-open.

**Comment by rtsuk** [comment]
I will have to open a new PR.

**Pull request closed without merging**
