### PR TITLE
fix a warning

### PR DESCRIPTION
**Pull request by eyelash**

### CODE REVIEW

**Comment by bkchr** [comment]
Because you initialize the value and not modify.

**Comment by cmyr** [comment]
@bkchr well we call `table.insert`, which requires table to be `mut`? Doesn't that count?

**Comment by raphlinus** [comment]
Because the type of `table` is `&mut HashMap<...>`.  I think this is valid.

**Comment by eyelash** [comment]
@cmyr I guess `table` is a mutable reference and does not need to be mutable itself. You only want to mutate the thing `table` points to and not the variable `table` itself. The following code compiles:
```rust
let mut x = HashMap::new();
let y = &mut x;
y.insert(1, 2);
```

**Comment by cmyr** [comment]
okay cool, thanks for walking me through this. 🙇

**Pull request merged**
