### PR TITLE
Added redesigned logo.

### PR DESCRIPTION
**Pull request by dragostis**

### CODE REVIEW

**Comment by dragostis** [comment]
@googlebot I've signed it.

**Comment by yaskhan** [comment]
I do not like. There is a better icons:
https://github.com/google/xi-editor/issues/51

**Comment by dragostis** [comment]
@yaskhan Not trying to be mean, but try to consider your reply a bit.

> I do not like.

Okay, I totally respect that. Someone on the internet does a language for a project for free, for fun, and you simply say that you don't like it without backing up your feedback without any constructive criticism. I may not take offense, but you might want to try a different approach when criticizing someone's work the next time because other people might. 😃 

> There is a better icons:

I did not know about the issue. It is my fault for not searching, but I was pretty sure there wouldn't be any because Xi is a very new project. The issue here is that, again, you're not backing up your assessment. If you think other icons are better, make sure you say why.

**Comment by PixelPirate** [comment]
[OS X Human Interface Guidelines - Icons](https://developer.apple.com/library/prerelease/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html#//apple_ref/doc/uid/20000957-CH87-SW1)

[Google Material Design Guidelines - Icons](https://material.google.com/style/icons.html#icons-system-icons)

One of the goals of this project is to use native UI on each platform, so I guess the main critique on your work is that it does not seem to fit with the general ascetic most icons have. (e.g.: The green rectangle background feels strange for a icon, at least for me)

**Comment by dragostis** [comment]
@PixelPirate Sure! The actual idea is not to use the as an icon, per se, but as a logo. Of course, you can change the shape/background. What I want to emphasize on is the idea to use part of the "X" to symbolize the cursor.

**Comment by dragostis** [comment]
@PixelPirate Here's an example of usage.

os x icon template 1 0

**Comment by raphlinus** [comment]
Thanks for the contribution! However, the best process for this is to get feedback on #51 and see if it's well-loved.

**Comment by beefsack** [comment]
Perhaps this one should be closed as a dupe in the meantime.

**Comment by raphlinus** [comment]
Kinda dropped the ball on this, sorry.

There's obviously not consensus to use this logo; I think we're gonna have to come back to #51 and have more discussion there.

@yaskhan I really want this to be a pleasant community to work in. So I do value your feedback, but ask that in the future you try to be a little more constructive and respectful of the effort our contributors put in. Thanks!

**Pull request closed without merging**
