### PR TITLE
Fix null cursor field in RPC

### LINKED ISSUE #200: Sending null cursor field in update (regression)
from @eyelash, [details here](https://github.com/google/xi-editor/pull/183/files/9523c4e41794fa246ae3a9edc47b749d7f549901#r111723790).

### PR DESCRIPTION
**Pull request by cmyr**
- resolves #200

### CODE REVIEW

**Comment by raphlinus** [comment]
Thanks!

**Comment by eyelash** [comment]
This changes the attribute name from `cursor` to `cursors`. Is this intentional?

**Comment by cmyr** [comment]
😞

**Comment by eyelash** [comment]
but I like the name change :smile:

**Comment by cmyr** [comment]
let's see what dad says

**Comment by raphlinus** [comment]
:) :) :)

"cursor" just because it's shorter and less disruptive, though I do like "cursors" as well.

**Pull request merged**
