### PR TITLE
Fix warnings in Xcode 7.3,Swift 2.2

### PR DESCRIPTION
**Pull request by chancyWu**

### CODE REVIEW

**Comment by chancyWu** [comment]
I signed it!

**Comment by raphlinus** [comment]
Thanks for the PR. Unfortunately, this breaks building in Xcode 7.2.1, which is what I have installed. At some point it'll make sense to roll it forward, but for now I think warnings are better than forcing a version of Xcode that not everyone might have.

**Comment by supermarin** [comment]
@raphlinus Xcode 7.3.1 is the newest one and there's no reason for people not to update to the newest Xcode / Swift IMO

**Comment by raphlinus** [comment]
Fair enough. I just upgraded my Xcode to 7.3 and this patch makes the build warning-free. Thanks!

**Pull request merged**
