### PR TITLE
WIP: Added logging support with Fern

### PR DESCRIPTION
**Pull request by betterclever**
First step towards #408 

Work in progress.

## Tasks

- [x] : add logging library
- [ ] : convert existing calls to stderr directly via eprintln macro to log calls.
- [ ] : log all RPC calls.  

@cmyr  Please affirm if I am heading in right direction. Thanks 😄

### CODE REVIEW

**Comment by cmyr** [comment]
This looks good! The one thing I'm noticing in the diff is that log4rs brings in a bunch of dependencies... I wonder if it might be worth looking at various other logging backends, like [slog](https://github.com/slog-rs/slog) or [fern](https://github.com/daboross/fern)? I don't really know much about the tradeoffs here, but that might be worth investigating.

**Comment by betterclever** [comment]
@cmyr I tried 2-3 implementations, almost all of them have their own dependencies as much as log4rs. Seeing more.

**Comment by cmyr** [comment]
@betterclever Okay, thanks for checking. If you think log4rs is the best fit then let's go with that. It looks like there are a lot of cargo features, so we might be able to turn some stuff off; we probably don't need file-based config, for instance.

**Comment by betterclever** [comment]
[stderrlog-rs](https://github.com/cardoe/stderrlog-rs) has less dependencies and is working fine. Updating PR soon.

**Comment by cmyr** [comment]
@betterclever We would like it to be possible to have logs written to file or to an internal buffer or something at some point. Basically: it should be relatively easy for the client to view the logs in real-time, for troubleshooting etc.

Not sure if stderrlog supports this, but if it _only_ supports logging to stderr it might not be adequate. :(

**Comment by betterclever** [comment]
Yeah. That would be an issue. In that case, a solution like log4rs seems
more fit. Let's implement this. Most log modules in Rust follow same log
facade thus switching later, if felt necessary, won't be a cumbersome task.

**Comment by cmyr** [comment]
@betterclever yep that sounds good to me.

**Comment by cmyr** [comment]
@betterclever re: IRC, I think log4rs is fine!

**Comment by cmyr** [comment]
@betterclever do you think you'll get a chance to revisit this at some point?

**Comment by betterclever** [comment]
Yeah. I would this weekend.

**Pull request closed without merging**
